### ISSUE TITLE
(//div)[position()=last()] returns the first div not the last 

### ISSUE THREAD

**Issue by cloando1** [Autonomiq/ChroPathFeedback#1]
I am experiencing that the function last() is not working with CroPath. 
I get the first entry always instead of the last one. 

The selector works perfectly when using it on Selenium. 

CroPath was very useful to me :) thanks!!!

**Comment by sanjayautonomiq** [comment]
This issue is fixed and pushed with 6.0 release. It is available in Chrome Store now. Please update the extension try.
