### ISSUE TITLE
Unable to find element with id that starts with digits using # selector

### ISSUE THREAD

**Issue by ostap-oleksyn** [Autonomiq/ChroPathFeedback#14]
If an element has an id that starts with digits(e.g. id="123gsr") chropath marks this css selector as invalid pattern - #123abc. This selector works fine - body[id='123gsr']
![pic](https://user-images.githubusercontent.com/11613015/84770532-63caed80-afe0-11ea-808a-be88903c0cc0.png)

**Comment by sanjayautonomiq** [comment]
The HTML 4.01 spec states that ID tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens (-), underscores (_), colons (:), and periods (.). For the class attribute, there is no such limitation. Classnames can contain any character, and they don’t have to start with a letter to be valid.

https://mathiasbynens.be/notes/html5-id-class#:~:text=The%20HTML%204.01%20spec%20states,there%20is%20no%20such%20limitation.

**Comment by ostap-oleksyn** [comment]
@sanjayautonomiq HTML 5 does not have those restrictions anymore, why not follow the newer web standard? Additionally it already works with this selector body[id='123gsr'], but not with #123gsr, which just seems inconsistent

**Comment by sanjayautonomiq** [comment]
Thank you @ostap-oleksyn for adding the details. It's not ChroPath issue if you check even Chrome DevTools won't support such cssSelector who's id starts with number.
Chrome DevTools will show 0 only even for invalid selector. But normal xpath will work as you mentioned.

![image](https://user-images.githubusercontent.com/44640750/84817576-d2389b80-b032-11ea-8075-67875df880e2.png)

**Comment by ostap-oleksyn** [comment]
Yeah, you're right, it does not work in chrome as well.
Anyway, thanks for taking a look at it.
