### ISSUE TITLE
Not able to download Chropath 6.0 Alpha version

### ISSUE THREAD

**Issue by BEKSundaram** [Autonomiq/ChroPathFeedback#2]
![errormessagefromchropathdownload](https://user-images.githubusercontent.com/57384199/68180014-1ac9aa00-ffb8-11e9-8f4f-81d770e11c62.jpg)

**Comment by sanjayautonomiq** [comment]
Yes there is issue in Windows and Ubuntu. It won't allow to download crx file, if you can get Mac then you can download it.
