### ISSUE TITLE
Downloaded excel throws file format error

### ISSUE THREAD

**Issue by SrkanpuSrikanthSrinivas** [Autonomiq/ChroPathFeedback#3]
Hi, I downloaded the first test case after recording and when i was trying to open the file it gives me file format error. Not sure if that is the same with all others. 

Below is the machine and browser version used

OS: MacOS Mojave
Version: 10.14.6
Chrome : Version 76.0.3809.100 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/35167347/68252122-41a0d400-ffea-11e9-8aaa-ec92aeef47fe.png)

Chropath is great 👍

**Comment by sanjayautonomiq** [comment]
Thank you for great finding. 
We are working on it, will push the fix soon. Appreciate your support.

**Comment by sanjayautonomiq** [comment]
Issue is fixed and pushed with 6.0. Available in production.
