### ISSUE TITLE
Chropath not working on Firefox 70+

### ISSUE THREAD

**Issue by aagoston18** [Autonomiq/ChroPathFeedback#4]
Hi @sanjayautonomiq 

I have tried every means possible to get this working with the latest Firefox but it won't load.

Steps I have tried:
- installed/reinstalled the plugin several times
- close and restart Firefox
- Uninstall / reinstall Firefox
- created new Firefox profile
- set the "accessibility.typeaheadfind.manual"  flag

Can you please take a look at what the issue is?

Thank you

System info:
Chropath 5.0.9 - from Mozilla Firefox addon-s page
Firefox 70.0.1 (64-bit)
MacOS Catalina 10.15 x64

**Comment by sanjayautonomiq** [comment]
ChroPath will show as sidebar. It seems you are trying to find it as separate tab like it was showing in older version of ChroPath for firefox.
Please follow this video tutorial-
https://www.youtube.com/watch?v=NVtb9HN-8Lc&feature

Kindly let me know if you face any issue.

![image](https://user-images.githubusercontent.com/44640750/68294296-cb69a380-00b5-11ea-89dd-b508fcf9b095.png)

![image](https://user-images.githubusercontent.com/44640750/68294335-e6d4ae80-00b5-11ea-9bfb-4992f9b8ce7a.png)

**Comment by aagoston18** [comment]
@sanjayautonomiq thank you for that, it was incredibly well hidden!! Love the product, keep up the good work :)
