### ISSUE TITLE
Chropath Studio:Getting Data value in steps when coping all data and paste it in excel

### ISSUE THREAD

**Issue by QETestEngineer** [Autonomiq/ChroPathFeedback#5]
![Screenshot_26](https://user-images.githubusercontent.com/20975959/70526483-b29a5500-1b6f-11ea-95c2-c51efd69d202.png)
In chropath studio when we copy all the data and pasting it in excel, we can see data value along with steps.

**Comment by sanjayautonomiq** [comment]
Issue is fixed and pushed with 6.0. Available in production.
