### ISSUE TITLE
Excel format issue:In Windows>Microsoft 2016

### ISSUE THREAD

**Issue by QETestEngineer** [Autonomiq/ChroPathFeedback#6]
Geeting error code when recoding and dowloading the steps file.When trying to open the file its throwing an error.
![Screenshot_24](https://user-images.githubusercontent.com/20975959/70526695-2dfc0680-1b70-11ea-8a57-a2c30eecc4c3.png)
PFA.
However i am facing this with window machine and with Office 2016.
Please let me know if anybody alse is facing the same..

**Comment by sanjayautonomiq** [comment]
Issue is fixed and pushed with 6.0. Available in production.
