### ISSUE TITLE
Chropath isn't working on font awesome 

### ISSUE THREAD

**Issue by badarmunir** [Autonomiq/ChroPathFeedback#7]
Chropath is unable to find xpath of fontawsome icons

**Comment by sanjayautonomiq** [comment]
Could you please share the url of the website and DOM of that element so that I can test it and fix for you. Thank you.

**Comment by badarmunir** [comment]
hi Sanjay
Website Url is:https://www.fulcrum-pk.com/
and when I clicked on social media icon using chropath recorder -I was
unable to find any XPath
Thank you

**Comment by sanjayautonomiq** [comment]
Thank you Badar for the details.
Yes you are right for few icons it is not capturing the actions on ChroPath Studio, will fix this issue asap.
Apart from this if you want the xpath only that you can see in chropath tab in devtools as shown in screenshot.

![image](https://user-images.githubusercontent.com/44640750/76402374-5f6fb280-63a9-11ea-9317-58de1bb51470.png)

![image](https://user-images.githubusercontent.com/44640750/76402301-3fd88a00-63a9-11ea-8332-75462e51f4dc.png)

**Comment by badarmunir** [comment]
Thank you Sanjay. Chropath is real help.  And thank you for your help and
quick response

**Comment by sanjayautonomiq** [comment]
Issue is fixed and pushed to Chrome Store. It will available very soon in 6.0.9 version.

**Comment by sanjayautonomiq** [comment]
Hi Badar,
Fix is live now. Please try it and let us know if any issue. Thank you.
Please update the ChroPath and try now.
